module.exports = {
    mode: "jit",
    purge: ["./src/**/*.{ts,tsx,js,jsx}"],
    darkMode: false,
    theme: {
        colors: {
            white: "#FFFFFF",
            blue: "#00A7E1",
            red: "#F32735",
            yellow: "#FFDA00",
            purple: "#180228",
            black: "#0D0D0D",
            "purple-light": "#341748",
        },
        fontSize: {
            xs: ["12px", { lineHeight: "auto" }],
            sm: ["14px"],
            base: ["16px", { lineHeight: "120%" }],
            lg: ["18px"],
            xl: ["20px", { lineHeight: "120%" }],
            "2xl": ["22px"],
            "2.5xl": ["22px", { letterSpacing: "0.1em" }],
            "3xl": ["24px"],
            "3.5xl": ["24px", { lineHeight: "130%" }],
            "4xl": ["30px"],
            "4.5xl": ["30px", { letterSpacing: "0.1em" }],
            "5xl": ["32px"],
            "6xl": ["36px"],
            "6.5xl": ["36px", { letterSpacing: "0.1em" }],
            "7xl": ["40px"],
            "8xl": ["42px"],
            "8.5xl": ["42px", { letterSpacing: "0.1em" }],
            "9xl": ["48px"],
            "9.5xl": ["48px", { letterSpacing: "0.1em" }],
            "10xl": ["50px"],
            "11xl": ["60px"],
            "11.5xl": ["60px", { letterSpacing: "0.1em" }],
            "12xl": ["64px"],
            "13xl": ["70px"],
            "14xl": ["80px"],
            "14.5xl": ["80px", { letterSpacing: "0.1em" }],
            "15xl": ["90px"],
            "15.5xl": ["90px", { letterSpacing: "0.1em" }],
            "16xl": ["96px"],
            "17xl": ["100px"],
            "17.5xl": ["100px", { letterSpacing: "0.1em" }],
        },
        fontFamily: {
            sofia: "Sofia Pro",
        },
        boxShadow: {
            steplix: "0 4px 20px 0 rgba(255, 255, 255, 0.25)",
        },
        extend: {},
    },
    variants: {
        extend: {},
    },
    plugins: [],
};
