name: build

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node version to use'
        type: string
        default: 14.18.0
        required: false
      artifact-repository:
        type: string
        description: "Value of first parameter to get. By default it uses output-dir"
        default: output-dir
        required: false



jobs:

  ### Running the build

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - run: npm ci
      - run: npm run release
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-repository }}
          path: out
          retention-days: 1
      - run: echo "BUILD SUCCESSFULLY"
