name: Create TAG

on:
  workflow_call:
    outputs:
      tag:
        description: "The tag created"
        value: ${{ jobs.tagging.outputs.tag }}

jobs:

  ### Running the TAG creation

  tagging:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.bumped_tag.outputs.version }}
    steps:
      - uses: steplix/cicd-get-parameter@v0.1.0
        id: args
        with:
          parameter-0: major
          parameter-1: minor

      - name: Get bumping mode
        id: bump-mode
        run: echo "mode=${{ steps.args.outputs.parameter-0 || steps.args.outputs.parameter-1 || 'patch' }}" >> $GITHUB_OUTPUT

      # Bump tag without affecting repository
      - uses: zwaldowski/semver-release-action@v3
        name: Get bumped tag
        id: bumped_tag
        with:
          dry_run: true
          bump: ${{ steps.bump-mode.outputs.mode }}
          github_token: ${{ secrets.GITHUB_TOKEN }}