name: Push Hotfix in master branch
run-name: >
  Push: ${{ github.ref_name }}

on:
  push:
    branches:
      - 'hotfix/**'


jobs:

  testing:
    uses: ./.github/workflows/test.yml
    with:
      node-version: ${{ vars.NODE_VERSION }}

  build:
    needs: [ testing ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - run: npm ci
      - run: npm run release

  generate-pr-to-master:
    needs: [testing,building]
    uses: ./.github/workflows/generate-pr.yml
    with:
      destination-branch-name: ${{ vars.DESTINATION_PR_ON_TESTING_WORKFLOW }}
      pr-title: "<patch> is TAG VERSION INCREMENT: Pushing HOTFIX ${{ github.ref_name }} into Master"

  generate-pr-to-develop:
    needs: [testing,building]
    uses: ./.github/workflows/generate-pr.yml
    with:
      destination-branch-name: ${{ vars.DESTINATION_PR_ON_DEVELOP_WORKFLOW }}
      pr-title: "Pushing HOTFIX ${{ github.ref_name }} into Develop"

  notify:
    if: ${{ always() }}
    needs: [ testing,building,generate-pr-to-master,generate-pr-to-develop ]
    uses: ./.github/workflows/notify.yml
    with:
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      slack-title: Push in MASTER branch
      slack-message: ${{ github.repository.url }}
      job-status: ${{ needs.testing.result || needs.build.result || needs.generate-pr-to-master.result || needs.generate-pr-to-develop.result }}
    secrets:
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}