name: Push in master branch

on:
  push:
    branches:
      - master


jobs:

  building:
    uses: ./.github/workflows/build.yml
    with:
      node-version: ${{ vars.NODE_VERSION }}
      artifact-repository: output

  tagging:
    uses: ./.github/workflows/create-tag.yml

  zipping:
    needs: [ tagging,building ]
    uses: ./.github/workflows/generate-zip.yml
    with:
      zip-name: ${{ needs.tagging.outputs.tag }}
      artifact-repository: output

  upload:
    needs: [ tagging,zipping ]
    uses: ./.github/workflows/uploadToS3.yml
    with:
      artifact-repository: ${{ needs.tagging.outputs.tag }}.tar.gz
      aws-bucket: ${{ vars.PROD_AWS_BUCKET_ARTIFACT }}
    secrets:
      aws-access-key-id: ${{ secrets.PROD_AWS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.PROD_AWS_REGION }}


  notify:
    if: ${{ always() }}
    needs: [ building,tagging,zipping,upload ]
    uses: ./.github/workflows/notify.yml
    with:
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      slack-title: Push in MASTER branch
      slack-message: ${{ github.repository.url }}
      job-status: ${{ needs.building.result || needs.tagging.result || needs.zipping.result || needs.upload.result }}
    secrets:
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}