name: Deployment to production

on:
  release:
    types: [published]


jobs:

  ## DEPLOY

  download-artifact-and-unzip:
    uses: ./.github/workflows/unzip.yml
    with:
      zip-name: ${{ github.event.release.tag_name }}
      artifact-repository: ${{ github.event.release.tag_name }}
      aws-bucket: ${{ vars.PROD_AWS_BUCKET_ARTIFACT }}
    secrets:
      aws-access-key-id: ${{ secrets.PROD_AWS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.PROD_AWS_REGION }}

  upload-to-production:
    needs: [ download-artifact-and-unzip ]
    uses: ./.github/workflows/uploadToS3.yml
    with:
      artifact-repository: ${{ github.event.release.tag_name }}
      aws-cloudfront-distribution-id: ${{ vars.PROD_AWS_CLOUDFRONT_DISTRIBUTION_ID }}
      aws-bucket: ${{ vars.PROD_AWS_BUCKET }}
    secrets:
      aws-access-key-id: ${{ secrets.PROD_AWS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.PROD_AWS_REGION }}


  notify:
    if: ${{ always() }}
    needs: [ download-artifact-and-unzip,upload-to-production ]
    uses: ./.github/workflows/notify.yml
    with:
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      slack-title: "DEPLOY to prod version: ${{ github.event.release.tag_name }}"
      slack-message: ${{ github.repository.url }}
      job-status: ${{ needs.download-artifact-and-unzip.result || needs.upload-to-production.result }}
    secrets:
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}