name: Push in general branches

on:
  push:
    branches:
      - 'feature/testCiCd'     # only for testCiCd branch

jobs:
  testing:
    uses: ./.github/workflows/test.yml
    with:
      node-version: 14.18.0

  notify:
    needs: testing
    uses: ./.github/workflows/notify.yml
    with:
      slack-channel: "test-cicd"
      slack-title: "Push Event"
      slack-message: ${{ github.repository.url }}
      job-status: ${{ needs.testing.result }}
    secrets:
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}